# Generated by Django 6.0.7 on 2026-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
